name: scan_gun
description: flutter实现扫码枪获取数据，禁止系统键盘弹窗
version: 1.0.5
author: lixiaohong<liyufengisme@gmail.com>
homepage: https://github.com/liyufengrex/flutter_scan_gun

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:

